[default]
ENV = "default"
TITLE = "Whoops"
SECRET_KEY = "Ix3867Ch4kl3"
EXTENSIONS = [
  "flask_bootstrap:Bootstrap",
  "src.ext.database:init_app",
  "src.ext.webui:init_app",
  "src.ext.actions:init_app",
]
